geekshop/authapp/urls.py
# from django.conf.urls import url

import authapp.views as authapp
from django.urls import re_path, path

app_name="authapp"

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^edit/$', authapp.edit, name='edit'),

    path('verify/<email>/<key>', authapp.verify, name='verify')
    
]

    

geekshop/geekshop/urls.py
# from django.conf.urls import url, include
from django.conf.urls import include
from django.contrib import admin
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path, path

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin')),

    path('order/', include('ordersapp.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
# from django.conf.urls import url

import mainapp.views as mainapp
from django.urls import re_path

app_name="mainapp"

urlpatterns = [
    re_path(r'^$', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),

    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.products, name='page'),

]

    

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name="ordersapp"

urlpatterns = [
   re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
   re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
   re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
   re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
   re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
   re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
]

geekshop/ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'
    DELIVERED = 'DVD'

    STATUSES = (
        (FORMING, 'Формируется'),
        (SENT_TO_PROCEED, 'Отправлен в обработку'),
        (PAID, 'Оплачен'),
        (PROCEEDED, 'Обработан'),
        (READY, 'Готов к выдаче'),
        (CANCEL, 'Отменен'),
        (DELIVERED, 'Выдан'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=3,
                              choices=STATUSES,
                              default=FORMING)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Current order: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    @staticmethod
    def get_item(pk):
        return Order.objects.get(pk=pk)


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="orderitems",
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    # def delete(self, *args, **kwargs):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super().delete(*args, **kwargs)
    #
    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.objects.get(pk=self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super().save(*args, **kwargs)

geekshop/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/ordersapp/views.py
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.shortcuts import render

from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            orderitems_formset = OrderFormSet(instance=self.object)
            for form in orderitems_formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.price.product.price
            data['orderitems'] = orderitems_formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['page_title'] = 'order/view'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))

@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=Order)
def products_quantity_update_save(sender, update_fields, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(pk=instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=Order)
def products_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

geekshop/ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
    <button class="btn btn-warning btn-round form-control last">
        <a href="{% url 'ordersapp:order_forming_complete' object.pk %}">
{#            совершить покупку#}
            purchase
        </a>
    </button>
{#    <button class="btn btn-default btn-round form-control last">#}
    <button class="btn btn-outline-secondary btn-sm form-control last">
        <a href="{% url 'ordersapp:order_delete' object.pk %}">
{#            удалить#}
            remove
        </a>
    </button>
{% endif %}
<button class="btn btn-info btn-round form-control last">
    <a href="{% url 'ordersapp:orders_list' %}">
{#        к списку заказов#}
        orders' list
    </a>
</button>
{#<button class="btn btn-default btn-round form-control last">#}
<button class="btn btn-outline-secondary btn-sm form-control last">
    <a href="{% url 'main:index' %}">
{#        на главную#}
        home
    </a>
</button>

geekshop/ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% load my_tags %}

{% if object %}
{#    <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>#}
    <div class="h2">Order №{{ object.pk }} from {{ object.created|date:"Y-m-d H:i:s" }}</div>
    <hr>
{#    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>#}
    <div class="h4">customer: {{ user.last_name }} {{ user.first_name }} </div>
{#    <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>#}
    <div class="h4">renewed: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
{#    <div class="h4">cтатус: {{ object.get_status_display }}</div>#}
    <div class="h4">status: {{ object.get_status_display }}</div>
    <hr>
    <div class="h4">
{#        общее количество товаров: <span class="order_total_quantity">{{ object.get_total_quantity }}</span>#}
        total quantity of goods: <span class="order_total_quantity">{{ object.get_total_quantity }}</span>
    </div>
    <div class="h3">
{#        общая стоимость: <span class="order_total_cost">{{ object.get_total_cost }}</span> руб#}
        total cost: <span class="order_total_cost">{{ object.get_total_cost|local_currency }}</span>
    </div>
{% else %}
{#    <div class="h2">Новый заказ</div>#}
    <div class="h2">New order</div>
    <hr>
{#    <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>#}
    <div class="h4">customer: {{ user.last_name }} {{ user.first_name }} </div>
    {% if basket.0 %}
        <div class="h4">
{#            общее количество товаров: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>#}
            total quantity of goods: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
        </div>
        <div class="h3">
{#            общая стоимость: <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб#}
            total cost: <span class="order_total_cost">{{ basket.0.get_total_cost|local_currency }}</span>
        </div>
    {% endif %}
{% endif %}
<hr>